// tslint:disable max-classes-per-file
export const namespace: string = "incident";

export class Mutations {
    public static SET_DICTIONARIES_FOR_CREATION = "SET_DICTIONARIES_FOR_CREATION";
    public static SET_DICTIONARIES_FOR_FILTER = "SET_DICTIONARIES_FOR_FILTER";
    public static SET_INCIDENTS = "SET_INCIDENTS";
    public static SET_FILTER = "SET_FILTER";
    public static SET_INCIDENT = "SET_INCIDENT";
    public static SET_STATUSES = "SET_STATUSES";
    public static SET_IS_LOADING = "SET_IS_LOADING";
    public static SET_INCIDENTS_TOTAL_ITEMS = "SET_INCIDENTS_TOTAL_ITEMS";
    public static SET_IS_RELATED_ARTICLES_LOADING = "SET_IS_RELATED_ARTICLES_LOADING";
    public static SET_IS_ARTICLE_PREVIEW_LOADING = "SET_IS_ARTICLE_PREVIEW_LOADING";
    public static SET_IS_ARTICLE_ATTACHING = "SET_IS_ARTICLE_ATTACHING";
    public static SET_IS_INCIDENT_LOADING = "SET_IS_INCIDENT_LOADING";
    public static SET_IS_INCIDENT_SAVING = "SET_IS_INCIDENT_SAVING";
}

export class Actions {
    public static FETCH_DICTIONARIES_FOR_CREATION = "FETCH_DICTIONARIES_FOR_CREATION";
    public static FETCH_DICTIONARIES_FOR_FILTER = "FETCH_DICTIONARIES_FOR_FILTER";
    public static FETCH_INCIDENTS = "FETCH_INCIDENTS";
    public static FETCH_INCIDENT = "FETCH_INCIDENT";
    public static SAVE_INCIDENT = "CREATE_INCIDENT";
    public static FETCH_STATUSES = "FETCH_STATUSES";
    public static SET_STATUS = "SET_STATUS";
    public static FETCH_HISTORY = "FETCH_HISTORY";
    public static FETCH_RELATED_ARTICLES = "FETCH_RELATED_ARTICLES";
    public static FETCH_ARTICLE_PREVIEW = "FETCH_ARTICLE_PREVIEW";
    public static ATTACH_ARTICLE_TO_INCIDENT = "ATTACH_ARTICLE_TO_INCIDENT";
    public static DETACH_ARTICLE_FROM_INCIDENT = "DETACH_ARTICLE_FROM_INCIDENT";
    public static FETCH_ATTACHED_ARTICLES = "FETCH_ATTACHED_ARTICLES";
    public static FETCH_STATISTICS = "FETCH_STATISTICS";
}

export class Getters {
    public static GET_DICTIONARIES_FOR_CREATION = "GET_DICTIONARIES_FOR_CREATION";
    public static GET_DICTIONARIES_FOR_FILTER = "GET_DICTIONARIES_FOR_FILTER";
    public static GET_NEW_FILTER = "GET_NEW_FILTER";
    public static GET_CURRENT_FILTER = "GET_CURRENT_FILTER";
    public static GET_INCIDENTS = "GET_INCIDENTS";
    public static INCIDENT = "INCIDENT";
    public static STATUSES = "STATUSES";
    public static GET_STATUS = "GET_STATUS";
    public static IS_LOADING = "IS_LOADING";
    public static INCIDENTS = "INCIDENTS";
    public static INCIDENTS_TOTAL_ITEMS = "SET_INCIDENTS_TOTAL_ITEMS";
    public static IS_RELATED_ARTICLES_LOADING = "IS_RELATED_ARTICLES_LOADING";
    public static IS_ARTICLE_PREVIEW_LOADING = "IS_ARTICLE_PREVIEW_LOADING";
    public static IS_ARTICLE_ATTACHING = "IS_ARTICLE_ATTACHING";
    public static IS_INCIDENT_LOADING = "IS_INCIDENT_LOADING";
    public static IS_INCIDENT_SAVING = "IS_INCIDENT_SAVING";
}
